apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: telemetry-aggregator-mlb-v1
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: dev
        app: telemetry-aggregator-mlb
        version: v1
        namespace: telemetry
        prefix: dev
        project: asf-development
        repo: telemetry-deployments

  template:
    metadata:
      name: '{{prefix}}-{{app}}-{{version}}'
    spec:
      project: '{{project}}'
      sources:
      - repoURL: '373797717611.dkr.ecr.eu-west-2.amazonaws.com'
        path: 'helm-charts/{{app}}'
        targetRevision: 0.1.0
        chart: 'helm-charts/{{app}}'
        helm:
          valueFiles:
            - $values/kubernetes/{{app}}-{{version}}/stages/{{stage}}/values.yaml
      - repoURL: 'https://github.com/MarkMckieAngstrom/{{repo}}.git'
        targetRevision: master
        ref: values
      - repoURL: 'https://github.com/MarkMckieAngstrom/{{repo}}.git'
        targetRevision: master
        path: kubernetes/{{app}}-{{version}}/stages/{{stage}}/additionalManifests
        
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}-{{stage}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
